### ISSUE TITLE
TT reading innacurately on rapid rapid inputs

### ISSUE THREAD

**Issue by Mechada2dx** [HWXLR8/beef-board#16]
When spinning the turntable slowly it cycles through fine. but when spinning faster, it looks like a temporal aliasing issue might be happening. Tried on a DAO PCB (SS001 V1.20) with the exact same setup, and I didn't encounter any issues similar to this one.

Going back to 72 teeth plate with the beef-board made everything work as it should.

**Comment by HWXLR8** [comment]
renaming this issue. Since we confirmed this also occurs on 80T plate, I am convinced this will occur on any TT given a rapid enough input. Characteristics of this failure are that given a rapid enough input frequency, TT reading will appear to slow down, and occasionally read the wrong direction. All of these are indicative of dropped inputs.
